name: Vulnerability scan

on:
  release:
    types:
      - published
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ github.repository }}:vuln-check
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
        with:
          image-ref: ${{ github.repository }}:vuln-check
          format: sarif
          output: trivy-results.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
